apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
  labels:
    app: ${PIPELINE_BUILD_IMAGE}
spec:
  replicas: ${PIPELINE_REPLICA}
  selector:
    matchLabels:
      app: ${PIPELINE_BUILD_IMAGE}
  template:
    metadata:
      labels:
        app: ${PIPELINE_BUILD_IMAGE}
    spec:
      nodeSelector:
       nodename: k8s-node-1
      containers:
        - name: ${PIPELINE_BUILD_IMAGE}
          image: ${PIPELINE_IMAGE}
          volumeMounts:
            - name: flexvol-mount
              mountPath: /mnt/storage
            - name: date-config
              mountPath: /etc/localtime
            - name: ekamedicare-mount
              mountPath: /mnt/Ekamedicare
            - name: mri-mount
              mountPath: /mnt/mri
          ports:
            - containerPort: 9092
      volumes:
        - name: flexvol-mount
          hostPath:
           path: /mnt/storage
        - name: date-config
          hostPath:
           path: /etc/localtime
        - name: ekamedicare-mount
          hostPath:
           path: /mnt/Ekamedicare
        - name: mri-mount
            hostPath:
              path: /mnt/mri
---
kind: Service
apiVersion: v1
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
spec:
  selector:
    app: ${PIPELINE_BUILD_IMAGE}
  type: NodePort
  ports:
    - port: ${PIPELINE_LOAD_BALANCER_PORT}
      protocol: TCP
      targetPort: 9092
