apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
  labels:
    app: ${PIPELINE_BUILD_IMAGE}
spec:
  replicas: ${PIPELINE_REPLICA}
  selector:
    matchLabels:
      app: ${PIPELINE_BUILD_IMAGE}
  template:
    metadata:
      labels:
        app: ${PIPELINE_BUILD_IMAGE}
    spec:
      containers:
        - name: ${PIPELINE_BUILD_IMAGE}
          image: ${PIPELINE_IMAGE}
          volumeMounts:
            - name: flexvol-mount
              mountPath: /mnt/storage
          ports:
            - containerPort: 9092
      volumes:
        - name: flexvol-mount
          persistentVolumeClaim:
            claimName: pvc-smb-flexvol
---
kind: Service
apiVersion: v1
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
spec:
  selector:
    app: ${PIPELINE_BUILD_IMAGE}
  type: NodePort
  ports:
    - nodePort: 30169
      port: ${PIPELINE_LOAD_BALANCER_PORT}
      protocol: TCP
      targetPort: 9092
