apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-${PIPELINE_BUILD_IMAGE}-conf
  namespace: ${PIPELINE_NAME_SPACE}
data:
  fluent.conf: |-
      <source>
        @type tail
        format none
        path /opt/logs/*.log
        pos_file /tmp/spring.pos
        tag boot
      </source>
      <match boot>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.elastic-kibana'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      index_name fluentd-monitoring-${PIPELINE_BUILD_IMAGE}
      type_name fluentd
      </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
  labels:
    app: ${PIPELINE_BUILD_IMAGE}
spec:
  replicas: ${PIPELINE_REPLICA}
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  selector:
    matchLabels:
      app: ${PIPELINE_BUILD_IMAGE}
  template:
    metadata:
      labels:
        app: ${PIPELINE_BUILD_IMAGE}
        fluentd-log-format: "springboot"
    spec:
      containers:
        - name: ${PIPELINE_BUILD_IMAGE}
          image: ${PIPELINE_IMAGE}
          volumeMounts:
            - name: flexvol-mount
              mountPath: /mnt/storage
            - name: medicare-mount
              mountPath: /mnt/Ekamedicare
            - name: ebserver-mount
              mountPath: /mnt/ebserver
            - name: springboot-log
              mountPath: /opt/logs
          ports:
            - containerPort: 9092
          resources:
           requests:
             memory: "50Mi"
             cpu: "500m"
           limits:
             memory: "500Mi"
             cpu: "2000m" 
        - name: fluentd
          imagePullPolicy: "Always"
          image: fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-elasticsearch7-1.1
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch.elastic-kibana"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_UID
              value: root
            - name: FLUENT_CONF
              value: fluent.conf
            - name: FLUENTD_ARGS
              value: -c /fluentd/etc/fluent.conf
          volumeMounts:
            - name: springboot-log
              mountPath: /opt/logs
            - name: fluentd-monitoring-hook-conf
              mountPath: /fluentd/etc/
      volumes:
        - name: flexvol-mount
          hostPath:
           path: /mnt/storage
        - name: medicare-mount
          hostPath:
           path: /mnt/Ekamedicare
        - name: ebserver-mount
          hostPath:
            path: /mnt/ebserver
        - name: fluentd-monitoring-hook-conf
          configMap:
            name: fluentd-${PIPELINE_BUILD_IMAGE}-conf
        - name: springboot-log
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
spec:
  selector:
    app: ${PIPELINE_BUILD_IMAGE}
  type: NodePort
  ports:
    - port: ${PIPELINE_LOAD_BALANCER_PORT}
      protocol: TCP
      targetPort: 9092
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${PIPELINE_BUILD_IMAGE}
  namespace: ${PIPELINE_NAME_SPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${PIPELINE_BUILD_IMAGE}
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
